function [frmProposal, noOfOFHTProp, ofhtBaseAngle, ofhtConf, motionFlag] = ...
    stComputeOfhtProposals( model, image, plattModel, ...
    prevBaseAngle, prevRegion, maxNoOfOfht, frmProposal, config, flags, ...
    noOfProp, prevMeanAngleConf, isNewTrack, prevMeanDeltaAngle, prevFlows)
% Compute and return geometrical proposals obtained from the optical flow
%
% INPUTS
%   model - an instance of TBDModel class
%   image - the current frame of the video
%   plattModel - an instance of PlattModel class
%   prevBaseAngle - rotation angle from previous result
%   prevRegion - bounding box region from the previous frame
%   maxNoOfOfht - maximum number of proposals to be generated
%   frmProposal - structure containing data about the proposals of the
%                 current frame
%   config - an instance of the Config class
%   flags - structure with binary valued flags
%   noOfProp - number of proposals already generated by other functions
%   prevMeanAngleConf - mean of previous angle confidences
%   isNewTrack - indicate if it is the first tracked frame of the video
%   prevMeanDeltaAngle - mean of previous angle changes
%   prevFlows - optical flows from last frame to current one
%
% OUTPUTS
%   frmProposal - updated structure containing data about the proposals of the
%                 current frame
%   noOfOFHTProp - number of proposals generated by this step
%   ofhtBaseAngle - array of angles, one for each proposal
%   ofhtConf - array of confidences, one for each proposal
%   motionFlag - boolean flag indicating if the motion was above the
%                threshold
%
% AUTHORS
%   Yang Hua (Yang.Hua@inria.fr)
%   Henrique Morimitsu (Henrique.Morimitsu@inria.fr)
%
% Licensed under the BSD 3-clause license [see license.txt]
%


    global VERBOSITY;

    [ofhtRegion, ofhtDet, ofhtRotIm, ofhtBaseAngle, ofhtConf, noOfOFHTProp, motionFlag] = ...
                        stOFHTProposalRotDetSmoothForMotion(prevRegion, prevFlows, isNewTrack, ...
                             model, maxNoOfOfht, prevBaseAngle, ...
                             prevMeanDeltaAngle, prevMeanAngleConf, image, config);

    if noOfOFHTProp ~= 0
        if flags.USE_PLATT_MAPPING_FLAG
            ofhtDet(:, 6) = plattModel.computePlattScaledScores(ofhtDet(:, 5));
        else
            ofhtDet(:, 6) = 0.0;
        end
        
        if VERBOSITY > 1
            fprintf('Geometrical proposals\n');
            printRectInfo(ofhtDet);
            printRegionInfo(ofhtRegion);
        end
        
        noOfOFHTProp = min(noOfOFHTProp, maxNoOfOfht);
        frmProposal = stAddFrmProposalData( frmProposal, noOfProp+1, noOfProp+noOfOFHTProp,...
            ofhtDet, ofhtRegion, ofhtBaseAngle, ofhtConf, ofhtRotIm );
    end % if noOfOFHTProp ~= 0

end

